"""upgrade sources

Revision ID: 46fadd5141ea
Revises: c4d701d273b1
Create Date: 2026-04-18 09:13:05.657556+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '46fadd5141ea'
down_revision: Union[str, Sequence[str], None] = 'c4d701d273b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'daily_checkin_enabled',
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'timezone',
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'timezone',
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'UTC'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'daily_checkin_enabled',
        existing_type=sa.BOOLEAN(),
        server_default=sa.text('true'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
