"""add_sources

Revision ID: 4b9975501b19
Revises: 46fadd5141ea
Create Date: 2026-04-18 09:32:24.548685+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b9975501b19'
down_revision: Union[str, Sequence[str], None] = '46fadd5141ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sources',
        sa.Column('source_file_name', sa.String(length=254), nullable=False),
        sa.Column(
            'source_type',
            sa.Enum('CR', 'BOOK', 'FOND', 'DOC', name='source_type_enum'),
            nullable=False,
        ),
        sa.Column('source_name', sa.String(length=254), nullable=False),
        sa.Column('source_date', sa.Integer(), nullable=False),
        sa.Column('source_url', sa.String(length=2048), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_name'),
        sa.UniqueConstraint('source_url'),
    )
    op.create_index(
        op.f('ix_sources_source_file_name'),
        'sources',
        ['source_file_name'],
        unique=True,
    )
    op.create_index(
        op.f('ix_sources_source_type'),
        'sources',
        ['source_type'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_file_name'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
