"""upgrade

Revision ID: 75bad0ff21c7
Revises: 46fadd5141ea
Create Date: 2026-04-18 09:28:11.674884+00:00

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '75bad0ff21c7'
down_revision: Union[str, Sequence[str], None] = '46fadd5141ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
