"""init

Revision ID: 8952f6dc74bf
Revises:
Create Date: 2026-04-15 17:52:43.117602+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8952f6dc74bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('phone', sa.String(length=16), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('hashed_password', sa.String(length=256), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column(
            'sex',
            sa.Enum('M', 'F', 'UNKNOWN', name='sex_enum'),
            nullable=False,
        ),
        sa.Column(
            'role',
            sa.Enum(
                'PATIENT', 'RELATIVE', 'DOCTOR', 'ADMIN', name='role_enum'
            ),
            nullable=False,
        ),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('stroke_date', sa.Date(), nullable=True),
        sa.Column('recurrent_stroke', sa.Boolean(), nullable=False),
        sa.Column(
            'stroke_type',
            sa.Enum(
                'ISCHEMIC', 'HEMORRHAGIC', 'UNKNOWN', name='stroke_type_enum'
            ),
            nullable=False,
        ),
        sa.Column(
            'stroke_toast_subtype',
            sa.Enum(
                'LAA',
                'CE',
                'LACUNAR',
                'OTHERDETERM',
                'OTHERUNDETERM',
                name='subtype_toast_enum',
            ),
            nullable=True,
        ),
        sa.Column(
            'stroke_hemo_subtype',
            sa.Enum('ICH', 'SAH', name='subtype_hem_enum'),
            nullable=True,
        ),
        sa.Column('medications', sa.JSON(), nullable=False),
        sa.Column('known_symptoms', sa.JSON(), nullable=False),
        sa.Column('doctor_id', sa.String(length=8), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table(
        'diary_entries',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'entry_type',
            sa.Enum(
                'BP',
                'BLOOD_TEST',
                'MEDICATION',
                'SYMPTOM',
                name='entry_type_enum',
            ),
            nullable=False,
        ),
        sa.Column('entry_json', sa.JSON(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_diary_entries_entry_type'),
        'diary_entries',
        ['entry_type'],
        unique=False,
    )
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('token_jti', sa.String(length=36), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token_jti'),
    )
    op.create_table(
        'reminders',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('reminder_type', sa.String(length=50), nullable=False),
        sa.Column('med_name', sa.String(length=255), nullable=True),
        sa.Column('time', sa.String(length=10), nullable=True),
        sa.Column('days', sa.JSON(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('refresh_tokens')
    op.drop_index(
        op.f('ix_diary_entries_entry_type'), table_name='diary_entries'
    )
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
