"""fix source model

Revision ID: 8c39db93cab4
Revises: 2b38fe8c2d5d
Create Date: 2026-04-18 14:44:02.000556+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c39db93cab4'
down_revision: Union[str, Sequence[str], None] = '2b38fe8c2d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sources', 'source_date', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'sources',
        'source_url',
        existing_type=sa.VARCHAR(length=2048),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sources',
        'source_url',
        existing_type=sa.VARCHAR(length=2048),
        nullable=False,
    )
    op.alter_column(
        'sources', 'source_date', existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
