"""notifs

Revision ID: c4d701d273b1
Revises: 5b1797b1adf4
Create Date: 2026-04-16 15:25:53.917402+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4d701d273b1'
down_revision: Union[str, Sequence[str], None] = '5b1797b1adf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'push_subscriptions',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('endpoint', sa.Text(), nullable=False),
        sa.Column('p256dh', sa.String(length=512), nullable=False),
        sa.Column('auth', sa.String(length=256), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.alter_column(
        'reminders',
        'time',
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Time(timezone=True),
        existing_nullable=True,
        postgresql_using='time::time with time zone',
    )
    op.add_column(
        'users',
        sa.Column(
            'daily_checkin_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'timezone',
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'UTC'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'daily_checkin_enabled')
    op.alter_column(
        'reminders',
        'time',
        existing_type=sa.Time(timezone=True),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
        postgresql_using='time::varchar',
    )
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###